name: Deploy Vite React to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your default branch is different

  # Allow manual triggers from GitHub UI
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5
          

          
